
version: '3.6'


networks:
  srv0: 
    driver: bridge

services:
  # telegraf:
  #   image: telegraf
  #   container_name: telegraf
  #   restart: always
  #   volumes:
  #   - ./config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
  #   depends_on:
  #     - influxdb
  #   # networks:
  #   #   - srv0
  #   network_mode: "host"
  #   ports:
  #   - '8125:8125'

  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    networks:
      - srv0
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:7.5.3
    container_name: grafana-server
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=http://github.com/geeks-r-us/mqtt-panel/releases/download/v1.0.7/geeksrus-mqtt-panel-1.0.7.zip;mqtt-panel
      - GF_PLUGINS_PLUGIN_ADMIN_ENABLED=true
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=geeksrus-mqtt-panel
    networks:
      - srv0
    ports:
      - '3001:3000'
    volumes:
      - grafana_data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    volumes:
      - ./config:/mosquitto/config:rw
      - ./data:/mosquitto/data:rw
      - ./log:/mosquitto/log:rw
    restart: unless-stopped
    networks:
        - srv0

  neuron:
    image: emqx/neuron:2.5.3-alpine
    container_name: neuron-alpine
    networks:
        - srv0
    ports:
      - "7001:7000"
    privileged: true
    restart: always

volumes:
  grafana_data: {}
  influxdb_data: {}

